matas_service_pairs = [
	('1', 'Iasm.'),
	('2', 'IIasm.'),
	('3', 'IIIasm.'),
	('akr.', ''),
	('arab.', ''),
	('asm.', ''),
	('aukšč.', ''),
	('aukšt.', ''),
	('bdv.', 'bdvr.'),
	('bendr.', ''),
	('bev.', 'bevrd.gim.'),
	('bndr.', 'bendr.gim.'),
	('būdn.', 'būdn.'),
	('būs.', 'būs.l.'),
	('būt-d.', 'būt.d.l.'),
	('būt-k', 'būt.kart.l.'),
	('būt.', 'būt.l.'),
	('daugin.', 'daugin.'),
	('dgs.', 'dgsk.'),
	('dkt.', 'dktv.'),
	('dll.', 'dll.'),
	('dlv.', 'dlv.'),
	('dvisk.', ''),
	('es.', 'esam.l.'),
	('G.', 'G.'),
	('Il.', 'Vt(ev).'),
	('Įn.', 'Įn.'),
	('išt.', 'ištk.'),
	('įv.', 'įvrd.'),
	('įvardž.', 'įvardž.'),
	('jng.', 'jngt.'),
	('jst.', 'jstk.'),
	('K.', 'K.'),
	('kelint.', 'kelintin.'),
	('kiek.', 'kiekin.'),
	('kita', ''),
	('kuopin.', ''),
	('liep.', ''),
	('mišr.', ''),
	('mot.', 'mot.gim.'),
	('N.', 'N.'),
	('neig.', ''),
	('nelygin.', ''),
	('neveik.', 'neveik.r.'),
	('pad.', 'padlv.'),
	('prl.', 'prln.'),
	('prv.', 'prvks.'),
	('pusd.', 'psdlv.'),
	('raid.', ''),
	('reik.', 'reikiamyb.'),
	('rom.', ''),
	('Š.', 'Š.'),
	('sampl.', ''),
	('sktv.', 'sktv.'),
	('skyr.', ''),
	('sngr.', 'sngr.'),
	('sutr.', 'sutrmp.'),
	('tar.', ''),
	('tęs.', ''),
	('tiesiog.', ''),
	('tikr.', 'T.'),
	('užs.', ''),
	('V.', 'V.'),
	('veik.', 'veik.r.'),
	('vksm.', 'vksm.'),
	('vns.', 'vnsk.'),
	('Vt.', 'Vt.'),
	('vyr.', 'vyr.gim.'),
]

matas_service_opposite_pairs = [
    ('įvardž.', 'neįvardž.'),
    ('sngr.', 'nesngr.')
]

service_matas_tag_map = { s:m for m, s in matas_service_pairs }
service_matas_tag_map.update( { s: None for _, s in matas_service_opposite_pairs } )